# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.19.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
accelerate_info:
  NOT AVAILABLE
blas_info:
    libraries = ['openblas.dll', 'blas']
    library_dirs = ['/opt/sagemath-9.2/local/lib', '/usr/lib']
    include_dirs = ['/usr/include', '/opt/sagemath-9.2/local/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['openblas.dll', 'blas']
    library_dirs = ['/opt/sagemath-9.2/local/lib', '/usr/lib']
    include_dirs = ['/usr/include', '/opt/sagemath-9.2/local/include']
    language = c
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
flame_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [6]:
vector = np.zeros((50,75))
print(f"{(vector.size * vector.itemsize)} bytes" )

30000 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
np.info(np.add) #python -c "import numpy as np; np.info(np.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [16]:
vector = np.arange(30)
vector = vector[::-1]
print(vector)

[29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6
  5  4  3  2  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [18]:
non_zeroes_indices = np.nonzero([1,2,0,0,4,0])
print(non_zeroes_indices)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [19]:
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [20]:
matrix = 100*np.random.random((3,3,3))
print(matrix)

[[[85.4726986  44.64160648 35.43729002]
  [ 7.16092348  6.01942057 18.46517284]
  [90.99646031 12.81904236 13.2326097 ]]

 [[68.87996165 26.81729161 36.89118749]
  [92.82494605 20.88323519  9.15324002]
  [35.99766543 13.07738452 30.52223139]]

 [[93.2637386   8.24016801 39.36973887]
  [70.85965507 63.02336872 23.3270509 ]
  [33.69330208 57.96708905 93.58802158]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [21]:
matrix = 100*np.random.random((10,10)).round(3)
print(matrix)
matrixrMin, matrixMax = matrix.min(), matrix.max()
print(f"Minimum is: {matrixrMin}; Maximum is {matrixMax}" )

[[ 2.1 17.2 18.6 22.4  9.7 20.9 64.1 20.8 80.7 69.7]
 [49.4 72.6 73.6  6.4 79.2 84.1  4.6 51.2 32.6  5.8]
 [98.9 97.2 13.2 20.2 13.  50.1 94.9 77.3 67.  68.7]
 [35.2  7.4 74.  41.7 33.1 49.8 32.  98.5  4.7 71.4]
 [74.6 38.6 80.5 15.7 80.9 81.9 92.3 23.4 32.8 57.5]
 [81.1 80.7 57.1 69.7 61.4 40.4 47.9 39.7 21.2 30.2]
 [90.8 73.4 77.2 23.6  2.9 23.2 64.4 86.  72.2 11.6]
 [15.2 35.5 50.8 51.7 23.3 77.  21.9 50.9 50.  78.7]
 [94.1 45.1 28.8 43.2 36.5 21.9 80.5 17.9 21.3 76.7]
 [21.1 63.6 34.8 55.   9.7 81.  53.8 21.8 49.3 26.5]]
Minimum is: 2.1; Maximum is 98.9


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [22]:
vector = 100*np.random.random(30).round(1)
print(vector)
avgValue = vector.mean()
print(avgValue)

[40. 80. 70. 20. 90. 40.  0. 10. 30. 50. 70. 90. 30. 40. 40. 50. 90. 10.
 40. 10. 40. 20. 80. 60. 30. 10. 90. 90. 20. 60.]
46.666666666666664


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [23]:
matrix = np.ones((10,10))
matrix[1:-1, 1:-1] = 0
print(matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [24]:
matrix = np.ones((5,5))
matrix = np.pad(matrix, pad_width=1, mode='constant', constant_values=0)
print(matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [25]:
print(f"0 * np.nan={0 * np.nan}")
print(f"np.nan == np.nan={np.nan == np.nan}")
print(f"np.inf > np.nan={np.inf > np.nan}")
print(f"np.nan - np.nan={np.nan - np.nan}")
print(f"np.nan in set([np.nan])={np.nan in set([np.nan])}")
print(f"0.3 == 3 * 0.1={0.3 == 3 * 0.1}")


0 * np.nan=nan
np.nan == np.nan=False
np.inf > np.nan=False
np.nan - np.nan=nan
np.nan in set([np.nan])=True
0.3 == 3 * 0.1=False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [26]:
matrix = np.diag(1+np.arange(4),k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [27]:
matrix = np.zeros((8,8),dtype=int)
matrix[1::2,::2] = 1
matrix[::2,1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [28]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [29]:
matrix = np.tile( np.array([ [0,1], [1,0] ]), (4,4))
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [31]:
matrix = np.random.random((5,5))
maxValue =matrix.max() 
matrix /= maxValue
matrix

array([[0.49730792, 0.71445893, 0.51876081, 0.42997619, 0.39558283],
       [0.15025815, 1.        , 0.86780158, 0.76060622, 0.93698363],
       [0.46577733, 0.35665593, 0.95796413, 0.79775487, 0.42882212],
       [0.10246135, 0.91387012, 0.03892863, 0.57676292, 0.83159379],
       [0.05788844, 0.9508892 , 0.30644976, 0.99959053, 0.56899391]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [32]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [33]:
matrix2 = np.ones((5,3)) @ np.ones((3,2))
print(matrix2)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [34]:
vector = np.arange(11)
vector[3:9] = np.multiply(vector[3:9],-1)
print(vector)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [35]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [36]:
Z = np.arange(10, dtype=int)
print(f"Z**Z = {Z**Z}")
print(f"2 << Z >> 2 = {2 << Z >> 2}")
print(f"Z <- Z = {Z <- Z}")
print(f"1j*Z = {1j*Z}")
print(f"Z/1/1 = {Z/1/1}")
print(f"Z<Z>Z = {Z<Z>Z}")

Z**Z = [        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
2 << Z >> 2 = [  0   1   2   4   8  16  32  64 128 256]
Z <- Z = [False False False False False False False False False False]
1j*Z = [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
Z/1/1 = [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [37]:
print(f"np.array(0) / np.array(0) = {np.array(0) / np.array(0)}")
print(f"np.array(0) // np.array(0) = {np.array(0) // np.array(0)}")
print(f"np.array([np.nan]).astype(int).astype(float) = {np.array([np.nan]).astype(int).astype(float)}")

np.array(0) / np.array(0) = nan
np.array(0) // np.array(0) = 0
np.array([np.nan]).astype(int).astype(float) = [-9.22337204e+18]


/opt/sagemath-9.2/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/opt/sagemath-9.2/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [40]:
vector = np.random.uniform(-10,10,10)
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 30. How to find common values between two arrays? (★☆☆)

In [41]:
vector1 = np.random.randint(10,40,10)
vector2 = np.random.randint(39,50,10)
print(np.intersect1d(vector1,vector2))

[39]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [42]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [43]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [44]:
_ = np.seterr(**defaults)

In [45]:
np.sqrt(-1) == np.emath.sqrt(-1)

/opt/sagemath-9.2/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [46]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(f"Yesterday: {yesterday}, Today: {today}. Tomorrow: {tomorrow}")

Yesterday: 2023-03-30, Today: 2023-03-31. Tomorrow: 2023-04-01


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [47]:
vectorDates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(vectorDates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [48]:
A = np.ones(5)*10
B = np.ones(5)*20
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-150., -150., -150., -150., -150.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [52]:
vector = np.random.uniform(0,10,10)
print(vector)
print(vector - vector%1)
print(vector // 1)
print(np.floor(vector))
print(vector.astype(int))

[2.2513866  6.25700782 7.86458285 7.83649987 5.20220022 4.7675847
 9.05885725 7.23173251 5.11327314 1.33797816]
[2. 6. 7. 7. 5. 4. 9. 7. 5. 1.]
[2. 6. 7. 7. 5. 4. 9. 7. 5. 1.]
[2. 6. 7. 7. 5. 4. 9. 7. 5. 1.]
[2 6 7 7 5 4 9 7 5 1]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [53]:
matrix = np.zeros((5,5))
matrix += np.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [54]:
def generate():
    for val in range(10):
        yield val
vector = np.fromiter(generate(), dtype=int)
print(vector)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [55]:
vector = np.linspace(0,1,11,endpoint=False)[1:]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [56]:
vector = 100* np.random.random(10)
vector.sort()
print(vector)

[ 6.30137092 40.60791994 42.16521234 45.13721304 50.66825048 57.40392248
 67.16466308 75.18401966 78.65782156 84.16236359]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [57]:
vector = np.arange(10)
print(vector)
np.add.reduce(vector)

[0 1 2 3 4 5 6 7 8 9]


45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [58]:
A = np.random.randint(0,10,10)
print(A)

B = np.random.randint(0,10,10)
print(B) 
print(np.array_equal(A,B))

[7 0 2 4 6 9 4 1 4 7]
[4 6 6 9 3 0 2 3 0 2]
False


#### 43. Make an array immutable (read-only) (★★☆)

In [59]:
vector = np.zeros(15)
vector.flags.writeable = False
vector[3] = 5

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [60]:
matrix = np.random.random((10,2))
X,Y = matrix[:,0], matrix[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.65090541 0.45224803 0.17007009 1.06133725 0.57427701 1.01592323
 0.29805745 0.36590432 0.19213301 0.61324261]
[0.29261742 0.02006576 0.29581807 0.82733964 0.20618037 0.9410891
 1.43528121 0.47019297 0.87250354 0.78983029]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [61]:
vector = np.random.random(10)
print(vector)
print()
vector[vector.argmax()] = 0
print(vector)

[0.26357354 0.86562046 0.94021946 0.93495759 0.74921692 0.98929223
 0.54781121 0.07657476 0.06798582 0.60459962]

[0.26357354 0.86562046 0.94021946 0.93495759 0.74921692 0.
 0.54781121 0.07657476 0.06798582 0.60459962]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [62]:
vector = np.zeros((6,6), [('x',float),('y',float)])
vector['x'], vector['y'] = np.meshgrid(np.linspace(0,1,6),
                             np.linspace(0,1,6))
print(vector)

[[(0. , 0. ) (0.2, 0. ) (0.4, 0. ) (0.6, 0. ) (0.8, 0. ) (1. , 0. )]
 [(0. , 0.2) (0.2, 0.2) (0.4, 0.2) (0.6, 0.2) (0.8, 0.2) (1. , 0.2)]
 [(0. , 0.4) (0.2, 0.4) (0.4, 0.4) (0.6, 0.4) (0.8, 0.4) (1. , 0.4)]
 [(0. , 0.6) (0.2, 0.6) (0.4, 0.6) (0.6, 0.6) (0.8, 0.6) (1. , 0.6)]
 [(0. , 0.8) (0.2, 0.8) (0.4, 0.8) (0.6, 0.8) (0.8, 0.8) (1. , 0.8)]
 [(0. , 1. ) (0.2, 1. ) (0.4, 1. ) (0.6, 1. ) (0.8, 1. ) (1. , 1. )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [63]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [64]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [65]:
vector = np.ones((10,10), dtype=int)
print(vector)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [66]:
vector = np.arange(100, 0, -2)
print(vector)
scalar = np.random.uniform(0,100)
print(scalar)
index = (np.abs(vector-scalar)).argmin()
print(vector[index])

[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2]
10.212187517590488
10


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [67]:
vector = np.zeros(10, [ ('position', [ ('x', float),
                                       ('y', float)]),
                       
                        ('color',    [ ('r', float),
                                       ('g', float),
                                       ('b', float)])])
print(vector)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [68]:
vector = np.random.random((25,2))
X,Y = np.atleast_2d(vector[:,0], vector[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.72873491 0.33829436 0.3315585  0.64775024 0.18619832
  0.66504632 0.21504778 0.26824671 0.27881641 0.69429107 0.58989385
  0.51458989 0.23483832 0.29652609 0.13907697 0.51375107 0.29334455
  0.38757148 0.25229939 0.27048115 0.78531701 0.32241218 0.26368497
  0.83585827]
 [0.72873491 0.         0.79701866 0.54131692 0.08971218 0.89634162
  0.44142412 0.51378614 0.77829019 0.74367136 0.03485719 0.23933114
  0.76890466 0.54921955 1.01919298 0.67066111 0.23818964 0.43582802
  0.40660762 0.78847417 0.45950565 0.46463698 1.04975216 0.78418992
  0.13238122]
 [0.33829436 0.79701866 0.         0.25570219 0.74129935 0.46062674
  0.53027713 0.39237265 0.07054565 0.61519374 0.76365939 0.58065196
  0.20588182 0.28030522 0.5041229  0.46312464 0.65520357 0.43357778
  0.60531887 0.59039358 0.41212593 0.64321866 0.49721483 0.60195894
  0.86320161]
 [0.3315585  0.54131692 0.25570219 0.         0.48728303 0.51362699
  0.33891011 0.22584603 0.24362179 0.54450758 0.50799764 0.32997136
  0.28

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [69]:
vectorFloats = (np.random.rand(10)*100).astype(np.float32)
print(vectorFloats)
vectorInts = vectorFloats.view(np.int32)
vectorInts[:] = vectorFloats
print(vectorInts)

[ 3.4260595 63.562855  88.14455   45.99377   67.98506   99.94867
 76.34492   34.860764  84.52984   27.544449 ]
[ 3 63 88 45 67 99 76 34 84 27]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [70]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
readFile = np.genfromtxt(s, delimiter=",", dtype=int)
print(readFile)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [71]:
matrix = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(matrix):
    print(index, value)
for index in np.ndindex(matrix.shape):
    print(index, matrix[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [72]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [73]:
n = 10
p = 3
matrix = np.zeros((n,n))
np.put(matrix, np.random.choice(range(n*n), p, replace=False),1)
print(matrix)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [74]:
X = np.random.rand(5, 10)
meanvalue = X.mean(axis=1, keepdims=True)
print(f"Mean value vector: {meanvalue}")
print()
Y = X - meanvalue
print(X)
print()
print(Y)


Mean value vector: [[0.37311431]
 [0.34516525]
 [0.44339594]
 [0.59056107]
 [0.50658493]]

[[0.4369263  0.73555262 0.1025355  0.48795527 0.15534534 0.23515974
  0.71078493 0.43567717 0.20355241 0.22765385]
 [0.92777038 0.19550233 0.14904466 0.08625208 0.33016279 0.30618641
  0.37739261 0.09619414 0.37898007 0.604167  ]
 [0.15973369 0.16548704 0.74244205 0.59837146 0.22530716 0.00859324
  0.56263307 0.51944199 0.49026462 0.96168504]
 [0.04107529 0.3324669  0.99518913 0.8441945  0.61239588 0.61204245
  0.83782757 0.9768946  0.35503877 0.29848566]
 [0.2609847  0.602127   0.82168139 0.25696083 0.62375094 0.94980333
  0.16851736 0.57131617 0.23589501 0.57481259]]

[[ 0.06381198  0.3624383  -0.27057881  0.11484096 -0.21776897 -0.13795457
   0.33767061  0.06256286 -0.1695619  -0.14546046]
 [ 0.58260513 -0.14966292 -0.19612059 -0.25891317 -0.01500245 -0.03897884
   0.03222736 -0.2489711   0.03381483  0.25900176]
 [-0.28366225 -0.27790889  0.29904611  0.15497552 -0.21808878 -0.43480269
   0.119

#### 59. How to sort an array by the nth column? (★★☆)

In [75]:
vector = np.random.randint(0,10,(3,3))
print(vector)
print()
print(vector[vector[:,1].argsort()])

[[7 3 9]
 [3 0 1]
 [5 6 0]]

[[3 0 1]
 [7 3 9]
 [5 6 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [76]:
matrix = np.random.randint(0,2,(5,10))
print(matrix)
print((~matrix.any(axis=0)).any())

[[0 1 0 1 1 1 1 0 0 1]
 [1 0 1 0 0 0 0 0 0 1]
 [1 1 0 0 1 1 0 1 1 1]
 [0 1 0 1 1 1 0 1 1 0]
 [1 1 1 1 1 1 1 0 0 1]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [77]:
matrix = np.random.uniform(0,1,10)
print(matrix)
givenValue = 0.5
print()
print(givenValue)
print()
nearestInArray = matrix.flat[np.abs(matrix - givenValue).argmin()]
print(nearestInArray)

[0.1566618  0.0773784  0.09423861 0.24755835 0.84753927 0.69907948
 0.61490251 0.73156738 0.16141879 0.00791062]

0.5

0.6149025126715455


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [78]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [79]:
class ArrayWithName(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

myArray = ArrayWithName(np.arange(10), "MyArrayName")
print (myArray.name)

MyArrayName


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [80]:
vector = np.ones(10)
print(vector)
indicesVec = np.random.randint(0,len(vector),20)
print(indicesVec)
vector += np.bincount(indicesVec, minlength=len(vector))
print(vector)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2 5 6 4 3 4 5 3 9 0 5 0 5 9 5 7 1 6 0 4]
[4. 2. 2. 3. 4. 6. 3. 2. 1. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [81]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [82]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [83]:
A = np.random.randint(0,10,(4,4,4,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[60 75 89 71]
 [67 68 86 75]
 [67 62 71 58]
 [67 78 66 86]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [84]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.43485219 0.56033798 0.51656771 0.65245703 0.56416777 0.51222211
 0.43363708 0.54470344 0.51623531 0.55895293]


#### 69. How to get the diagonal of a dot product? (★★★)

In [85]:
A = 100*np.random.uniform(0,1,(5,5))
print(A)
print()
B = 100*np.random.uniform(0,1,(5,5))
print(B)
print()
print(np.sum(A * B.T, axis=1))
print(np.diag(np.dot(A, B)))


[[59.60416818 96.85709884 91.97104957 26.49211871 82.40128996]
 [33.73778174 60.8095778  30.05882679 44.24005668 59.26806816]
 [38.32252321 27.13414596 49.32898976 22.30598559 88.54696866]
 [ 1.42345373 81.98567052 98.1443341  15.21326184  3.2850984 ]
 [36.14010506 56.11391016 48.5114718  14.20031994 52.91466059]]

[[84.26443796 68.74706909 10.15537336 67.35287931 73.04752839]
 [36.12466318 51.1431446  33.15743389 15.3822693  92.92323636]
 [ 8.96252     5.38318816 58.86437413 46.80086447  3.80522263]
 [46.15261729 17.82651284 93.77626468 30.42282135 79.16479136]
 [63.04461448  2.94510683 67.71612444 13.79766874 37.98785247]]

[15763.3723499   6554.37569378 12280.427849    6458.39609585
 11173.1081222 ]
[15763.3723499   6554.37569378 12280.427849    6458.39609585
 11173.1081222 ]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [86]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [87]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [88]:
A = np.arange(25).reshape(5,5)
A[[0,4]] = A[[4,0]]
print(A)

[[20 21 22 23 24]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [89]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0,  6) ( 0, 95) ( 6, 95) (14, 32) (14, 95) (23, 25) (23, 61) (24, 73)
 (24, 90) (25, 26) (25, 41) (25, 61) (26, 41) (32, 36) (32, 55) (32, 95)
 (36, 55) (45, 66) (45, 90) (47, 52) (47, 82) (52, 82) (59, 63) (59, 72)
 (63, 72) (66, 81) (66, 90) (73, 90) (81, 90)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [90]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [91]:
def moving_average(a, n) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

vector = np.arange(20)
print(moving_average(vector, n=4))

[ 1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5 14.5
 15.5 16.5 17.5]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [92]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
vector = rolling(np.arange(10), 3)
print(vector)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [93]:
vector = np.random.uniform(-1.0,1.0,10)
print(vector)
print()
print(np.negative(vector, out=vector))

[ 0.15781333  0.9981882   0.17322368  0.37251481 -0.50490219 -0.13866537
  0.74131923  0.59667772  0.40756432 -0.46235676]

[-0.15781333 -0.9981882  -0.17322368 -0.37251481  0.50490219  0.13866537
 -0.74131923 -0.59667772 -0.40756432  0.46235676]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [94]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 6.66649925 10.0919383  14.8846268   0.14524873  8.54314853  3.24686287
  0.50998899  9.87500113  0.33222425  4.2039835 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [98]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[15.90706955  0.04680512 21.83989039  3.95518105 16.49410638  4.30224329
  12.54800569  0.14360481  3.02377492 12.99540121]
 [ 6.2045868   7.15399375 12.75134544  0.39830251 10.97925723  5.48536207
   4.48840075  6.3224302   7.87156407  3.45896099]
 [ 9.92515181  0.52409336 15.41337515  2.19547038 10.04768871  1.56560811
   5.87844878  0.20402065  1.61924341  9.53977121]
 [ 2.90885748  0.91124672  7.8155065   9.66278234  2.26415178  8.43595185
   2.06855107  0.91527998  0.34893055  5.66358192]
 [ 1.21780606  5.3822792   4.24961826 10.25239453  1.02759229 12.65945161
   4.87738442  3.22609406  3.31234329  0.72510893]
 [13.79300395  0.96017591 19.33143907  0.78224693 13.33778395  2.27649687
   9.7007463   1.17752389  1.26101952 12.47284013]
 [ 2.57770143  7.80711159  8.920211    3.85241908  7.31246781  9.05630364
   0.57953148  6.4415274   7.36859906  1.1714463 ]
 [ 0.56305372  9.06896781  5.75072706  6.21964741  4.68543454 12.17858867
   2.4993501   7.29285433  7.72376698  1.24571786]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [99]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[7 2 7 4 8 3 1 1 9 1]
 [2 3 0 4 0 7 5 5 3 8]
 [8 9 6 6 3 7 9 8 0 7]
 [3 5 6 4 6 8 1 6 1 8]
 [4 1 0 7 5 8 2 3 3 6]
 [7 9 0 9 0 4 0 2 6 5]
 [9 7 5 9 7 9 0 1 1 7]
 [7 1 9 1 9 8 2 3 9 7]
 [6 1 1 0 3 0 4 7 6 4]
 [4 3 1 7 7 7 0 4 1 9]]
[[0 0 0 0 0]
 [0 7 2 7 4]
 [0 2 3 0 4]
 [0 8 9 6 6]
 [0 3 5 6 4]]


/opt/sagemath-9.2/local/lib/python3.7/site-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [100]:
vector = np.arange(1,15,dtype=np.uint32)
stridedMatrix = stride_tricks.as_strided(vector,(11,4),(4,4))
print(stridedMatrix)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [101]:
matrix = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(matrix)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [102]:
vector = np.random.randint(0,10,50)
print(np.bincount(vector).argmax())

8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [106]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 1 4]
   [4 2 2]
   [4 4 1]]

  [[1 4 0]
   [2 2 4]
   [4 1 0]]

  [[4 0 1]
   [2 4 0]
   [1 0 1]]

  [[0 1 2]
   [4 0 1]
   [0 1 0]]

  [[1 2 4]
   [0 1 1]
   [1 0 2]]

  [[2 4 4]
   [1 1 1]
   [0 2 2]]

  [[4 4 1]
   [1 1 1]
   [2 2 4]]

  [[4 1 2]
   [1 1 3]
   [2 4 0]]]


 [[[4 2 2]
   [4 4 1]
   [2 2 4]]

  [[2 2 4]
   [4 1 0]
   [2 4 1]]

  [[2 4 0]
   [1 0 1]
   [4 1 0]]

  [[4 0 1]
   [0 1 0]
   [1 0 2]]

  [[0 1 1]
   [1 0 2]
   [0 2 3]]

  [[1 1 1]
   [0 2 2]
   [2 3 0]]

  [[1 1 1]
   [2 2 4]
   [3 0 0]]

  [[1 1 3]
   [2 4 0]
   [0 0 0]]]


 [[[4 4 1]
   [2 2 4]
   [2 3 1]]

  [[4 1 0]
   [2 4 1]
   [3 1 2]]

  [[1 0 1]
   [4 1 0]
   [1 2 4]]

  [[0 1 0]
   [1 0 2]
   [2 4 2]]

  [[1 0 2]
   [0 2 3]
   [4 2 3]]

  [[0 2 2]
   [2 3 0]
   [2 3 2]]

  [[2 2 4]
   [3 0 0]
   [3 2 1]]

  [[2 4 0]
   [0 0 0]
   [2 1 2]]]


 [[[2 2 4]
   [2 3 1]
   [2 2 2]]

  [[2 4 1]
   [3 1 2]
   [2 2 0]]

  [[4 1 0]
   [1 2 4]
   [2 0 1]]

  [[1 0 2]
   [2 4 2]
   [0 1 0]]

  [[0 2 3]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [107]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 9 10  4 13  3]
 [10  3  8  6 10]
 [ 4  8  1 42  5]
 [13  6 42  4 16]
 [ 3 10  5 16  9]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [108]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [109]:
vector = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(vector, np.arange(0, vector.shape[0], k), axis=0),
                                       np.arange(0, vector.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [110]:
def iterate(vector):
    N = (vector[0:-2,0:-2] + vector[0:-2,1:-1] + vector[0:-2,2:] +
         vector[1:-1,0:-2]                + vector[1:-1,2:] +
         vector[2:  ,0:-2] + vector[2:  ,1:-1] + vector[2:  ,2:])

    birth = (N==3) & (vector[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (vector[1:-1,1:-1]==1)
    vector[...] = 0
    vector[1:-1,1:-1][birth | survive] = 1
    return vector

vector = np.random.randint(0,2,(50,50))
for i in range(100): vector = iterate(vector)
print(vector)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [111]:
vector = np.arange(10000)
np.random.shuffle(Z)
n = 10
print(vector[np.argsort(vector)[-n:]])
print(vector[np.argpartition(-vector,n)[:n]])

[9990 9991 9992 9993 9994 9995 9996 9997 9998 9999]
[9992 9996 9993 9998 9991 9994 9995 9997 9999 9990]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [112]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [113]:
vector = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
record = np.core.records.fromarrays(vector.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(record)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [114]:
x = np.random.rand(int(5e6))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

117 ms ± 1.24 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
49.1 ms ± 1.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
27.7 ms ± 1.43 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [115]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 2 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [116]:
matrix = np.random.randint(0,5,(10,3))
print(matrix)

E = np.all(matrix[:,1:] == matrix[:,:-1], axis=1)
U = matrix[~E]
print(U)
U = matrix[matrix.max(axis=1) != matrix.min(axis=1),:]
print(U)

[[0 2 0]
 [2 1 0]
 [3 1 2]
 [2 0 1]
 [0 3 0]
 [2 1 0]
 [4 4 2]
 [0 2 4]
 [4 0 0]
 [2 1 3]]
[[0 2 0]
 [2 1 0]
 [3 1 2]
 [2 0 1]
 [0 3 0]
 [2 1 0]
 [4 4 2]
 [0 2 4]
 [4 0 0]
 [2 1 3]]
[[0 2 0]
 [2 1 0]
 [3 1 2]
 [2 0 1]
 [0 3 0]
 [2 1 0]
 [4 4 2]
 [0 2 4]
 [4 0 0]
 [2 1 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [117]:
intVector = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(intVector[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [118]:
matrix = np.random.randint(0,2,(6,3))
uniqueMatrix = np.unique(matrix, axis=0)
print(uniqueMatrix)

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [119]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.11704316, 0.01514475, 0.00264706, 0.10915846, 0.10063628,
        0.15922311, 0.11872288, 0.08155429, 0.07213661, 0.06927522],
       [0.32504658, 0.04205927, 0.0073513 , 0.30314958, 0.27948219,
        0.44218668, 0.32971142, 0.22648862, 0.20033428, 0.19238777],
       [0.53048154, 0.06864144, 0.01199744, 0.49474527, 0.45611969,
        0.72165619, 0.53809464, 0.36963328, 0.32694896, 0.31398011],
       [0.63586711, 0.08227776, 0.01438086, 0.59303146, 0.54673252,
        0.86502054, 0.64499263, 0.4430647 , 0.3919007 , 0.37635545],
       [0.44920341, 0.05812449, 0.01015925, 0.41894249, 0.38623497,
        0.61108708, 0.45565006, 0.31299964, 0.27685522, 0.2658734 ],
       [0.0549556 , 0.00711096, 0.00124288, 0.05125348, 0.04725204,
        0.07476048, 0.05574429, 0.03829242, 0.0338705 , 0.03252699],
       [0.56534716, 0.07315287, 0.01278597, 0.52726214, 0.48609792,
        0.76908666, 0.57346063, 0.39392724, 0.3484375 , 0.33461628],
       [0.08321364, 0.0107674 , 0.0018819

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [120]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)               
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)      
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [121]:
X = np.asarray([[4.0, 2.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [122]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.38836411  0.05114372]
